---
- name: Restore playbook.yml
  hosts: all
  gather_facts: false
  vars_files:
    - vars/web.yml
  tasks:


    - name: 1) 방화벽 종료 - {{ fw_webs }}
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      loop: "{{ fw_webs }}"


    - name: 2) 서비스 종료 - {{ svc_web }}, {{ svc_fw }}
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop: "{{ svcs }}"


    - name: 3) 서비스 설정 삭제
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html/.htaccess
        - /etc/httpd/secrets
        - /var/www/html/index.html


    - name: 4) 패키지 삭제 - {{ pkg_http }}, {{ pkg_https }}
      ansible.builtin.dnf:
        name: 
          - httpd
          - mod_ssl
        state: absent
